---
title: "string and factors"
output: github_document
---


```{r}
library(tidyverse)
library(rvest)

library(p8105.datasets)

```


## do strings
```{r}
string_vec = c("my","name","is","SQ")

str_detect(string_vec,"a")

str_replace(string_vec,"SQ", "sq")
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "^i think")
str_detect(string_vec, "i think")
```


```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"[Pp]umpkin")

str_detect(string_vec,"pumpkin")

str_detect(string_vec,"Pumpkin")

```


```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "^[0-9][a-zA-Z]")
str_detect(string_vec, "[0-9][a-z]")
```


```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11") # . matches everything
```



```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[") # "\\" Some characters are “special”. These include [ and ], ( and ), and .. If you want to search for these, you have to indicate they’re special using \. Unfortunately, \ is also special, so things get weird.
```

```{r}
sex_vec=factor(c("male","male","female","female"))
as.numeric(sex_vec)
```

```{r}
sex_vec = fct_relevel(sex_vec, "male")
as.numeric(sex_vec)
```


## revisit lots of examples
```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url)

drug_use_html
```

```{r}
major_use_df = 
  drug_use_html |>
  html_table() |>
  first() |>
  slice(-1)|>
  select(-contains("P Value"))|>
  pivot_longer(
    cols= -State,
    names_to = "age_year",
    values_to = "percent"
  )|>
  separate(age_year, into = c("age", "year"), sep = "\\(")|>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_remove(percent,"[a-c]$"),
    percent = as.numeric(percent)
  )
```

```{r}
major_use_df|>
  filter(
    age == "12-17"
    )|>
  mutate(
    State = fct_reorder(State,percent)
  ) |>
  ggplot(aes(x=State, y = percent, color = year))+
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5,hjust = 1))
```

## NYC restaurant 
```{r}
data("rest_inspec")
```

```{r}
rest_inspec |> 
  count(boro, grade) |>
  pivot_wider(
    names_from = grade,
    values_from = n
  )
```


```{r}
rest_inspec = 
  rest_inspec|>
  filter(
    str_detect(grade, "[A-C]"),
    !(boro=="Missing")
  )
```

```{r}
rest_inspec|>
  mutate(dba = str_to_sentence(dba)) |>
  filter(str_detect(dba,"Pizza"))
```

```{r}
rest_inspec|>
  mutate(dba = str_to_sentence(dba)) |>
  filter(str_detect(dba,"Pizza"))|>
  mutate(boro = fct_relevel(boro,"STATEN ISLAND"))|>
  ggplot(aes(x= boro))+
  geom_bar()
```

```{r}
rest_inspec|>
  mutate(dba = str_to_sentence(dba)) |>
  filter(str_detect(dba,"Pizza"))|>
  mutate(
     boro = fct_infreq(boro),
    boro = str_replace(boro, "Manhattan", "The City")) |>
  ggplot(aes(x= boro))+
  geom_bar()
```

```{r}
rest_inspec |> 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) |>
  mutate(
    boro = fct_infreq(boro),
    boro = fct_recode(boro, "The City" = "MANHATTAN"),
    ) |>
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar()
```

```{r}
rest_inspec|>
  mutate(dba = str_to_sentence(dba))|>
  filter(str_detect(dba,"Pizza"))|>
  lm(formula( = zipcode ~ boro, data =_ ))
```

```{r}

```

